/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as StudentRouteImport } from './routes/student'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeacherIndexRouteImport } from './routes/teacher.index'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as TeacherStudentsRouteImport } from './routes/teacher.students'
import { Route as TeacherCompareRouteImport } from './routes/teacher.compare'
import { Route as TeacherAlertsRouteImport } from './routes/teacher.alerts'
import { Route as StudentPredictionsRouteImport } from './routes/student.predictions'
import { Route as StudentPerformanceRouteImport } from './routes/student.performance'
import { Route as StudentActivityRouteImport } from './routes/student.activity'

const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherIndexRoute = TeacherIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeacherRoute,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const TeacherStudentsRoute = TeacherStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherCompareRoute = TeacherCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherAlertsRoute = TeacherAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => TeacherRoute,
} as any)
const StudentPredictionsRoute = StudentPredictionsRouteImport.update({
  id: '/predictions',
  path: '/predictions',
  getParentRoute: () => StudentRoute,
} as any)
const StudentPerformanceRoute = StudentPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => StudentRoute,
} as any)
const StudentActivityRoute = StudentActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => StudentRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/student': typeof StudentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/student/activity': typeof StudentActivityRoute
  '/student/performance': typeof StudentPerformanceRoute
  '/student/predictions': typeof StudentPredictionsRoute
  '/teacher/alerts': typeof TeacherAlertsRoute
  '/teacher/compare': typeof TeacherCompareRoute
  '/teacher/students': typeof TeacherStudentsRoute
  '/student/': typeof StudentIndexRoute
  '/teacher/': typeof TeacherIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/student/activity': typeof StudentActivityRoute
  '/student/performance': typeof StudentPerformanceRoute
  '/student/predictions': typeof StudentPredictionsRoute
  '/teacher/alerts': typeof TeacherAlertsRoute
  '/teacher/compare': typeof TeacherCompareRoute
  '/teacher/students': typeof TeacherStudentsRoute
  '/student': typeof StudentIndexRoute
  '/teacher': typeof TeacherIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/student': typeof StudentRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/student/activity': typeof StudentActivityRoute
  '/student/performance': typeof StudentPerformanceRoute
  '/student/predictions': typeof StudentPredictionsRoute
  '/teacher/alerts': typeof TeacherAlertsRoute
  '/teacher/compare': typeof TeacherCompareRoute
  '/teacher/students': typeof TeacherStudentsRoute
  '/student/': typeof StudentIndexRoute
  '/teacher/': typeof TeacherIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/student'
    | '/teacher'
    | '/student/activity'
    | '/student/performance'
    | '/student/predictions'
    | '/teacher/alerts'
    | '/teacher/compare'
    | '/teacher/students'
    | '/student/'
    | '/teacher/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/student/activity'
    | '/student/performance'
    | '/student/predictions'
    | '/teacher/alerts'
    | '/teacher/compare'
    | '/teacher/students'
    | '/student'
    | '/teacher'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/student'
    | '/teacher'
    | '/student/activity'
    | '/student/performance'
    | '/student/predictions'
    | '/teacher/alerts'
    | '/teacher/compare'
    | '/teacher/students'
    | '/student/'
    | '/teacher/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  StudentRoute: typeof StudentRouteWithChildren
  TeacherRoute: typeof TeacherRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/': {
      id: '/teacher/'
      path: '/'
      fullPath: '/teacher/'
      preLoaderRoute: typeof TeacherIndexRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/teacher/students': {
      id: '/teacher/students'
      path: '/students'
      fullPath: '/teacher/students'
      preLoaderRoute: typeof TeacherStudentsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/compare': {
      id: '/teacher/compare'
      path: '/compare'
      fullPath: '/teacher/compare'
      preLoaderRoute: typeof TeacherCompareRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/alerts': {
      id: '/teacher/alerts'
      path: '/alerts'
      fullPath: '/teacher/alerts'
      preLoaderRoute: typeof TeacherAlertsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/student/predictions': {
      id: '/student/predictions'
      path: '/predictions'
      fullPath: '/student/predictions'
      preLoaderRoute: typeof StudentPredictionsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/performance': {
      id: '/student/performance'
      path: '/performance'
      fullPath: '/student/performance'
      preLoaderRoute: typeof StudentPerformanceRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/activity': {
      id: '/student/activity'
      path: '/activity'
      fullPath: '/student/activity'
      preLoaderRoute: typeof StudentActivityRouteImport
      parentRoute: typeof StudentRoute
    }
  }
}

interface StudentRouteChildren {
  StudentActivityRoute: typeof StudentActivityRoute
  StudentPerformanceRoute: typeof StudentPerformanceRoute
  StudentPredictionsRoute: typeof StudentPredictionsRoute
  StudentIndexRoute: typeof StudentIndexRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentActivityRoute: StudentActivityRoute,
  StudentPerformanceRoute: StudentPerformanceRoute,
  StudentPredictionsRoute: StudentPredictionsRoute,
  StudentIndexRoute: StudentIndexRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

interface TeacherRouteChildren {
  TeacherAlertsRoute: typeof TeacherAlertsRoute
  TeacherCompareRoute: typeof TeacherCompareRoute
  TeacherStudentsRoute: typeof TeacherStudentsRoute
  TeacherIndexRoute: typeof TeacherIndexRoute
}

const TeacherRouteChildren: TeacherRouteChildren = {
  TeacherAlertsRoute: TeacherAlertsRoute,
  TeacherCompareRoute: TeacherCompareRoute,
  TeacherStudentsRoute: TeacherStudentsRoute,
  TeacherIndexRoute: TeacherIndexRoute,
}

const TeacherRouteWithChildren =
  TeacherRoute._addFileChildren(TeacherRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  StudentRoute: StudentRouteWithChildren,
  TeacherRoute: TeacherRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
