import { createFileRoute } from "@tanstack/react-router";
import { Panel } from "@/components/Card";
import { teacherAlerts, students } from "@/lib/mock-data";
import { AlertTriangle, Flame, TrendingDown } from "lucide-react";

export const Route = createFileRoute("/teacher/alerts")({
  head: () => ({ meta: [{ title: "Alerts — EduAI" }, { name: "description", content: "AI alerts and topic weakness analysis." }] }),
  component: Alerts,
});

const heat = ["Algebra","Calculus","Physics","Chemistry","Programming","Statistics"].map((s, i) => ({
  topic: s, intensity: Math.round(40 + (i * 17) % 60),
}));

function Alerts() {
  const atRisk = students.filter(s => s.risk === "high");

  return (
    <div className="space-y-10">
      <header className="space-y-1.5 pb-2 border-b border-border/40">
        <h1 className="text-3xl md:text-4xl font-bold tracking-tight flex items-center gap-3">AI Alerts <Flame className="size-7 text-warning" /></h1>
        <p className="text-muted-foreground">Real-time risk detection & topic weakness analysis.</p>
      </header>

      <div className="grid md:grid-cols-2 gap-6">
        <Panel title="Active Alerts" subtitle="Generated by AI engine">
          <div className="space-y-3">
            {teacherAlerts.map((a, i) => {
              const tone = a.type === "high" ? "destructive" : a.type === "medium" ? "warning" : "success";
              return (
                <div key={i} className={`flex items-start gap-3 p-4 rounded-xl bg-${tone}/10 border border-${tone}/30`}>
                  <div className={`size-9 rounded-lg bg-${tone}/20 text-${tone} flex items-center justify-center shrink-0`}>
                    <AlertTriangle className="size-4" />
                  </div>
                  <div>
                    <div className="text-sm font-medium">{a.text}</div>
                    <div className="text-xs text-muted-foreground mt-0.5 capitalize">{a.type} priority · just now</div>
                  </div>
                </div>
              );
            })}
          </div>
        </Panel>

        <Panel title="Topic Weakness Heatmap" subtitle="Class-wide concept retention">
          <div className="space-y-3">
            {heat.map((t) => (
              <div key={t.topic} className="flex items-center gap-3">
                <div className="w-28 text-sm text-muted-foreground">{t.topic}</div>
                <div className="flex-1 h-7 rounded-lg bg-muted overflow-hidden relative">
                  <div className={`h-full ${t.intensity > 70 ? "bg-destructive/70" : t.intensity > 50 ? "bg-warning/70" : "bg-success/60"}`} style={{ width: `${t.intensity}%` }} />
                  <span className="absolute inset-0 flex items-center justify-end pr-2 text-xs font-medium tabular-nums">{t.intensity}% weak</span>
                </div>
              </div>
            ))}
          </div>
        </Panel>
      </div>

      <Panel title="At-Risk Students" subtitle={`${atRisk.length} students flagged`}>
        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">
          {atRisk.map((s) => (
            <div key={s.id} className="glass rounded-xl p-4 border-destructive/30 hover:border-destructive/60 transition-colors">
              <div className="flex items-start justify-between">
                <div>
                  <div className="font-medium">{s.name}</div>
                  <div className="text-xs text-muted-foreground">Semester {s.semester} · {s.id}</div>
                </div>
                <span className="text-xs px-2 py-0.5 rounded-full bg-destructive/15 text-destructive border border-destructive/30 flex items-center gap-1">
                  <TrendingDown className="size-3" /> {s.trend}%
                </span>
              </div>
              <div className="mt-3 flex items-center gap-3 text-sm">
                <span className="text-muted-foreground">Retention</span>
                <span className="font-bold tabular-nums">{s.retention}%</span>
              </div>
              <div className="mt-1 flex flex-wrap gap-1">
                {s.weakSubjects.map((w) => (
                  <span key={w} className="text-xs px-2 py-0.5 rounded-md bg-warning/10 text-warning border border-warning/30">{w}</span>
                ))}
              </div>
            </div>
          ))}
          {atRisk.length === 0 && <div className="col-span-full text-center py-8 text-muted-foreground">No at-risk students 🎉</div>}
        </div>
      </Panel>
    </div>
  );
}
